from typing import Any, Optional

class PyDatabase:
    @staticmethod
    def open(path: str, shard_count: Optional[int] = None) -> "PyDatabase": ...
    def put(self, key: bytes, doc: bytes, valid_from: int, valid_to: int) -> int: ...
    def get(
        self, key: bytes, as_of: Optional[int] = None, valid_at: Optional[int] = None
    ) -> Optional[bytes]: ...
    def sql(self, query: str) -> Any: ...
    def ask(self, question: str) -> dict[str, Any]: ...
