/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare class JsDatabase {
  static open(path: string, shardCount?: number | undefined | null): JsDatabase
  put(key: Buffer, doc: Buffer, validFrom: number, validTo: number): number
  get(key: Buffer, asOf?: number | undefined | null, validAt?: number | undefined | null): Buffer | null
  /** Execute SQL and return JSON string result. */
  sql(query: string): string
}
