#!/usr/bin/env python3
"""Fine-tune Qwen3-0.6B for TensorDB NL→SQL with QLoRA.

Usage:
    conda run -n cortex_ngc python scripts/finetune_nl2sql.py

Expects training_data.jsonl and eval_data.jsonl in the same directory
(generated by generate_training_data.py).

Output: scripts/output/tensordb-nl2sql/ (adapter + merged model)
"""

import json
import os
from pathlib import Path

import torch
from datasets import Dataset
from peft import LoraConfig, TaskType, get_peft_model, prepare_model_for_kbit_training
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    BitsAndBytesConfig,
    TrainingArguments,
)
from trl import SFTTrainer, SFTConfig

SCRIPT_DIR = Path(__file__).resolve().parent
OUTPUT_DIR = SCRIPT_DIR / "output" / "tensordb-nl2sql"
MERGED_DIR = OUTPUT_DIR / "merged"

BASE_MODEL = "Qwen/Qwen3-0.6B"
MAX_SEQ_LENGTH = 512


def load_jsonl(path: Path) -> list[dict]:
    """Load a JSONL file into a list of dicts."""
    data = []
    with open(path) as f:
        for line in f:
            line = line.strip()
            if line:
                data.append(json.loads(line))
    return data


def format_chatml(messages: list[dict]) -> str:
    """Format messages into ChatML string for training."""
    parts = []
    for msg in messages:
        role = msg["role"]
        content = msg["content"]
        parts.append(f"<|im_start|>{role}\n{content}<|im_end|>")
    return "\n".join(parts)


def main():
    print(f"Device: {torch.cuda.get_device_name(0) if torch.cuda.is_available() else 'CPU'}")
    print(f"CUDA available: {torch.cuda.is_available()}")
    if torch.cuda.is_available():
        print(f"GPU memory: {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f} GB")

    # ---- Load data ----
    train_path = SCRIPT_DIR / "training_data.jsonl"
    eval_path = SCRIPT_DIR / "eval_data.jsonl"

    if not train_path.exists():
        raise FileNotFoundError(
            f"{train_path} not found. Run generate_training_data.py first."
        )

    train_data = load_jsonl(train_path)
    eval_data = load_jsonl(eval_path) if eval_path.exists() else []

    print(f"Training examples: {len(train_data)}")
    print(f"Eval examples: {len(eval_data)}")

    # Format into ChatML strings
    train_texts = [format_chatml(ex["messages"]) for ex in train_data]
    eval_texts = [format_chatml(ex["messages"]) for ex in eval_data]

    train_dataset = Dataset.from_dict({"text": train_texts})
    eval_dataset = Dataset.from_dict({"text": eval_texts}) if eval_texts else None

    # ---- Load tokenizer ----
    print(f"\nLoading tokenizer: {BASE_MODEL}")
    tokenizer = AutoTokenizer.from_pretrained(BASE_MODEL, trust_remote_code=True)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token
    tokenizer.padding_side = "right"

    # ---- Load model with 4-bit quantization ----
    print(f"Loading model: {BASE_MODEL} (4-bit NF4)")
    bnb_config = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_quant_type="nf4",
        bnb_4bit_compute_dtype=torch.bfloat16,
        bnb_4bit_use_double_quant=True,
    )

    model = AutoModelForCausalLM.from_pretrained(
        BASE_MODEL,
        quantization_config=bnb_config,
        device_map="auto",
        trust_remote_code=True,
        dtype=torch.bfloat16,
    )
    model = prepare_model_for_kbit_training(model)

    # ---- LoRA configuration ----
    lora_config = LoraConfig(
        task_type=TaskType.CAUSAL_LM,
        r=32,
        lora_alpha=64,
        lora_dropout=0.05,
        target_modules=[
            "q_proj", "k_proj", "v_proj", "o_proj",
            "gate_proj", "up_proj", "down_proj",
        ],
        bias="none",
    )

    model = get_peft_model(model, lora_config)
    model.print_trainable_parameters()

    # ---- Training config ----
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    training_args = SFTConfig(
        output_dir=str(OUTPUT_DIR),
        num_train_epochs=3,
        per_device_train_batch_size=8,
        gradient_accumulation_steps=2,  # effective batch = 16
        learning_rate=2e-4,
        lr_scheduler_type="cosine",
        warmup_ratio=0.05,
        bf16=True,
        logging_steps=25,
        save_strategy="epoch",
        eval_strategy="epoch" if eval_dataset else "no",
        save_total_limit=2,
        max_length=MAX_SEQ_LENGTH,
        dataset_text_field="text",
        packing=False,
        report_to="none",
        seed=42,
        gradient_checkpointing=True,
        optim="adamw_torch",
    )

    # ---- Train ----
    print("\nStarting training...")
    trainer = SFTTrainer(
        model=model,
        args=training_args,
        train_dataset=train_dataset,
        eval_dataset=eval_dataset,
        processing_class=tokenizer,
    )

    trainer.train()
    trainer.save_model(str(OUTPUT_DIR))
    tokenizer.save_pretrained(str(OUTPUT_DIR))
    print(f"\nAdapter saved to: {OUTPUT_DIR}")

    # ---- Merge LoRA into base model ----
    print(f"\nMerging LoRA adapter into base model...")
    from peft import PeftModel

    # Reload base model in fp16 for merging (no quantization)
    base_model = AutoModelForCausalLM.from_pretrained(
        BASE_MODEL,
        dtype=torch.float16,
        device_map="auto",
        trust_remote_code=True,
    )

    merged_model = PeftModel.from_pretrained(base_model, str(OUTPUT_DIR))
    merged_model = merged_model.merge_and_unload()

    MERGED_DIR.mkdir(parents=True, exist_ok=True)
    merged_model.save_pretrained(str(MERGED_DIR))
    tokenizer.save_pretrained(str(MERGED_DIR))
    print(f"Merged model saved to: {MERGED_DIR}")

    print("\nDone! Next step: run convert_to_gguf.sh to produce the GGUF file.")


if __name__ == "__main__":
    main()
